version: '3'

services:
  app:
    # name: visual-field-mapper
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.10-bullseye
    image: erikwithuhk/visual-field-mapper
    container_name: visual-field-mapper
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    user: vscode
